# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e93341b19428c74263b24cff245fbb97d2dbd92d463e9904411b72ccc1c9c993ca92c5d570832137aff4e6d21408e8dd85f1f9fab05725581f566bffc1681584

test:
  secret_key_base: 6cb3227bf04f70ae08e0d1203f5394fac7f8facebb03dd84141d0a1639e5ff8f904e086e6127bc2579136ad2707a7c38c807e2b6d1bcb909682fca9d7ef38312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
